figma.showUI(__uiFiles__.main, { width: 600, height: 720 });

let currentLanguage = 'en';

const COLOR_BLIND_TYPE_KEYS = ['normal', 'protanopia', 'deuteranopia', 'tritanopia', 'protanomaly', 'deuteranomaly', 'tritanomaly'];

const LOCALE = {
  en: {
    fonts: {
      title: { family: 'Inter', style: 'Bold' },
      body: { family: 'Inter', style: 'Regular' },
      card: { family: 'Inter', style: 'Bold' }
    },
    report: {
      frameName: 'Accessibility Report',
      title: 'Accessibility Report',
      description: 'These simulations show how users with different color vision deficiencies may perceive your design. Use this report to spot low-contrast areas and color-dependent issues.',
      footerPrefix: 'Generated by CVT',
      footerTime: 'Generated at'
    },
    notifications: {
      selectNode: 'Please select a node first',
      generating: 'Generating report...',
      generated: '✅ Report generated!',
      failed: '❌ Failed to generate: ',
      unknown: 'Unknown error',
      loadFont: 'Unable to load a font required for report export'
    },
    colorTypes: {
      normal: { reportTitle: 'Original', reportDescription: 'Typical vision rendering' },
      protanopia: { reportTitle: 'Protanopia', reportDescription: 'Reduced sensitivity to red, often appears darker' },
      deuteranopia: { reportTitle: 'Deuteranopia', reportDescription: 'Reduced sensitivity to green, a common type' },
      tritanopia: { reportTitle: 'Tritanopia', reportDescription: 'Reduced sensitivity to blue, relatively rare' },
      protanomaly: { reportTitle: 'Protanomaly', reportDescription: 'Reduced red sensitivity' },
      deuteranomaly: { reportTitle: 'Deuteranomaly', reportDescription: 'Reduced green sensitivity, relatively common' },
      tritanomaly: { reportTitle: 'Tritanomaly', reportDescription: 'Reduced blue sensitivity' }
    }
  },
  zh: {
    fonts: {
      title: { family: 'Songti TC', style: 'Bold' },
      body: { family: 'PingFang SC', style: 'Regular' },
      card: { family: 'PingFang SC', style: 'Semibold' }
    },
    report: {
      frameName: '无障碍报告',
      title: '无障碍报告',
      description: '这些模拟展示了有各种视觉障碍的用户是如何感知您的设计，使用本报告来识别低对比度区域或颜色障碍问题。',
      footerPrefix: '由CVT生成',
      footerTime: '生成时间'
    },
    notifications: {
      selectNode: '请先选择一个节点',
      generating: '正在生成报告...',
      generated: '✅ 报告已生成！',
      failed: '❌ 生成失败: ',
      unknown: '未知错误',
      loadFont: '无法加载导出报告所需字体'
    },
    colorTypes: {
      normal: { reportTitle: '原图', reportDescription: '正常视觉效果' },
      protanopia: { reportTitle: '红色盲', reportDescription: '红色不敏感，看起来更暗' },
      deuteranopia: { reportTitle: '绿色盲', reportDescription: '绿色不敏感，常见色盲类型' },
      tritanopia: { reportTitle: '蓝色盲', reportDescription: '蓝色不敏感，比较罕见' },
      protanomaly: { reportTitle: '红色弱', reportDescription: '红色感知能力低' },
      deuteranomaly: { reportTitle: '绿色弱', reportDescription: '绿色感知能力弱，较常见' },
      tritanomaly: { reportTitle: '蓝色弱', reportDescription: '蓝色感知能力低' }
    }
  }
};

function locale() {
  return LOCALE[currentLanguage] || LOCALE.en;
}

function localizedColorBlindTypes() {
  return COLOR_BLIND_TYPE_KEYS.map(function(key) {
    var typeInfo = locale().colorTypes[key];
    return {
      key: key,
      reportTitle: typeInfo.reportTitle,
      reportDescription: typeInfo.reportDescription
    };
  });
}

const ISHIHARA_UI_ASSETS = [
  { code: '02', svg: __uiFiles__.plate02 },
  { code: '05', svg: __uiFiles__.plate05 },
  { code: '07', svg: __uiFiles__.plate07 },
  { code: '08', svg: __uiFiles__.plate08 },
  { code: '12', svg: __uiFiles__.plate12 },
  { code: '16', svg: __uiFiles__.plate16 },
  { code: '29', svg: __uiFiles__.plate29 },
  { code: '35', svg: __uiFiles__.plate35 },
  { code: '45', svg: __uiFiles__.plate45 },
  { code: '74', svg: __uiFiles__.plate74 },
  { code: '96', svg: __uiFiles__.plate96 }
];

function postIshiharaAssetsToUI() {
  for (var i = 0; i < ISHIHARA_UI_ASSETS.length; i++) {
    figma.ui.postMessage({
      type: 'ishihara-asset',
      code: ISHIHARA_UI_ASSETS[i].code,
      svg: ISHIHARA_UI_ASSETS[i].svg
    });
  }

  figma.ui.postMessage({
    type: 'ishihara-assets-complete',
    count: ISHIHARA_UI_ASSETS.length
  });
}

postIshiharaAssetsToUI();

const REPORT_COLORS = {
  pageBg: hexToRgb('#F5F0E8'),
  cardBg: hexToRgb('#FFFFFF'),
  title: hexToRgb('#141413'),
  secondary: hexToRgb('#8E8B82'),
  body: hexToRgb('#8E8B82'),
  imageStroke: hexToRgb('#000000'),
  imageStrokeOpacity: 0.08,
  shadow: rgbaToFigma(0, 0, 0, 0.10)
};

function hexToRgb(hex) {
  const clean = hex.replace('#', '');
  return {
    r: parseInt(clean.slice(0, 2), 16) / 255,
    g: parseInt(clean.slice(2, 4), 16) / 255,
    b: parseInt(clean.slice(4, 6), 16) / 255
  };
}

function rgbaToFigma(r, g, b, a) {
  return {
    r: r / 255,
    g: g / 255,
    b: b / 255,
    a
  };
}

async function loadPreferredFont(preferred) {
  const fallbacks = [
    preferred,
    { family: 'PingFang SC', style: 'Semibold' },
    { family: 'PingFang SC', style: 'Regular' },
    { family: 'Songti SC', style: 'Bold' },
    { family: 'Songti TC', style: 'Bold' },
    { family: 'Alibaba PuHuiTi 3.0', style: 'Regular' },
    { family: 'Inter', style: 'Bold' },
    { family: 'Inter', style: 'Regular' }
  ];

  for (const font of fallbacks) {
    try {
      await figma.loadFontAsync(font);
      return font;
    } catch (error) {}
  }

  throw new Error(locale().notifications.loadFont);
}

function createTextNode(parent, characters, options) {
  const node = figma.createText();
  node.fontName = options.fontName;
  node.characters = characters;
  node.fontSize = options.fontSize;
  node.fills = [{ type: 'SOLID', color: options.color }];
  node.x = options.x;
  node.y = options.y;
  if (options.width) {
    node.resize(options.width, node.height);
    node.textAutoResize = 'HEIGHT';
  } else {
    node.textAutoResize = 'WIDTH_AND_HEIGHT';
  }
  parent.appendChild(node);
  return node;
}

async function getImageFromSelection() {
  const selection = figma.currentPage.selection;
  
  if (selection.length === 0) {
    figma.ui.postMessage({ type: 'no-selection' });
    return;
  }

  const node = selection[0];
  
  try {
    if ('fills' in node && node.fills) {
      const fills = Array.isArray(node.fills) ? node.fills : [node.fills];
      const imageFill = fills.find(fill => fill && fill.type === 'IMAGE');
      
      if (imageFill && imageFill.imageHash) {
        const image = figma.getImageByHash(imageFill.imageHash);
        if (image) {
          const bytes = await image.getBytesAsync();
          figma.ui.postMessage({ 
            type: 'image-data', 
            data: bytes
          });
          return;
        }
      }
    }
    
    const bytes = await node.exportAsync({ 
      format: 'PNG', 
      constraint: { type: 'SCALE', value: 2 }
    });
    figma.ui.postMessage({ 
      type: 'image-data', 
      data: bytes
    });
    
  } catch (error) {
    console.error('Error getting image:', error);
  }
}

figma.on('selectionchange', getImageFromSelection);

figma.ui.onmessage = async (msg) => {
  if (msg.type === 'get-image') {
    getImageFromSelection();
  } else if (msg.type === 'request-ishihara-assets') {
    postIshiharaAssetsToUI();
  } else if (msg.type === 'set-language') {
    currentLanguage = msg.language === 'zh' ? 'zh' : 'en';
  } else if (msg.type === 'generate-report') {
    const selection = figma.currentPage.selection;
    if (selection.length === 0) {
      figma.notify(locale().notifications.selectNode);
      return;
    }
    figma.notify(locale().notifications.generating);
    
    const bytes = await selection[0].exportAsync({ 
      format: 'PNG', 
      constraint: { type: 'SCALE', value: 1 }
    });
    
    figma.ui.postMessage({
      type: 'prepare-simulations',
      data: bytes
    });
    
  } else if (msg.type === 'create-report') {
    await createReportWithImages(msg.images);
  }
};

async function createReportWithImages(simulatedImages) {
  try {
    const cols = 4;
    const pagePadding = 40;
    const gridGap = 24;
    const cardPadding = 24;
    const cardWidth = 812;
    const cardHeight = 940;
    const imageSize = 764;
    const gridTop = 280;
    const headerWidth = 1568;
    const frameWidth = 3400;
    const frameHeight = 2360;

    const titleFont = await loadPreferredFont(locale().fonts.title);
    const regularFont = await loadPreferredFont(locale().fonts.body);
    const boldCardFont = await loadPreferredFont(locale().fonts.card);
    const reportCopy = locale().report;
    const reportTypes = localizedColorBlindTypes();
    
    const reportFrame = figma.createFrame();
    reportFrame.name = reportCopy.frameName;
    reportFrame.resize(frameWidth, frameHeight);
    reportFrame.x = figma.viewport.center.x - frameWidth / 2;
    reportFrame.y = figma.viewport.center.y - frameHeight / 2;
    reportFrame.cornerRadius = 16;
    reportFrame.fills = [{ type: 'SOLID', color: REPORT_COLORS.pageBg }];
    reportFrame.effects = [{
      type: 'DROP_SHADOW',
      color: REPORT_COLORS.shadow,
      offset: { x: 0, y: 4 },
      radius: 12,
      spread: 0,
      visible: true,
      blendMode: 'NORMAL'
    }];

    const timestamp = new Intl.DateTimeFormat(currentLanguage === 'zh' ? 'zh-CN' : 'en-US', {
      year: 'numeric',
      month: '2-digit',
      day: '2-digit',
      hour: '2-digit',
      minute: '2-digit',
      second: '2-digit',
      hour12: true
    }).format(new Date());

    const titleNode = createTextNode(reportFrame, reportCopy.title, {
      fontName: titleFont,
      fontSize: 88,
      color: REPORT_COLORS.title,
      x: 41.36,
      y: 41.17
    });
    titleNode.strokes = [{ type: 'SOLID', color: REPORT_COLORS.title }];
    titleNode.strokeWeight = 1.2;

    createTextNode(
      reportFrame,
      reportCopy.description,
      {
        fontName: regularFont,
        fontSize: 32,
        color: REPORT_COLORS.body,
        x: 41.36,
        y: 184.17,
        width: headerWidth
      }
    );
    
    for (let i = 0; i < reportTypes.length; i++) {
      const type = reportTypes[i];
      const imgData = simulatedImages[i];
      
      const col = i % cols;
      const row = Math.floor(i / cols);
      
      const x = pagePadding + col * (cardWidth + gridGap);
      const y = gridTop + row * (cardHeight + gridGap);

      const card = figma.createRectangle();
      card.resize(cardWidth, cardHeight);
      card.x = x;
      card.y = y;
      card.cornerRadius = 24;
      card.fills = [{ type: 'SOLID', color: REPORT_COLORS.cardBg }];
      reportFrame.appendChild(card);
      
      const imageHash = figma.createImage(imgData).hash;
      const imgRect = figma.createRectangle();
      imgRect.resize(imageSize, imageSize);
      imgRect.x = x + cardPadding;
      imgRect.y = y + cardPadding;
      imgRect.cornerRadius = 16;
      imgRect.fills = [{ 
        type: 'IMAGE', 
        scaleMode: 'FILL', 
        imageHash: imageHash 
      }];
      imgRect.strokes = [{ type: 'SOLID', color: REPORT_COLORS.imageStroke, opacity: REPORT_COLORS.imageStrokeOpacity }];
      imgRect.strokeWeight = 1;
      reportFrame.appendChild(imgRect);

      createTextNode(reportFrame, type.reportTitle, {
        fontName: boldCardFont,
        fontSize: 32,
        color: REPORT_COLORS.title,
        x: x + cardPadding,
        y: y + 812,
        width: imageSize
      });

      createTextNode(reportFrame, type.reportDescription, {
        fontName: regularFont,
        fontSize: 24,
        color: REPORT_COLORS.secondary,
        x: x + cardPadding,
        y: y + 860,
        width: imageSize
      });
    }

    createTextNode(reportFrame, `${reportCopy.footerPrefix} ${reportCopy.footerTime} ${timestamp}`, {
      fontName: regularFont,
      fontSize: 24,
      color: REPORT_COLORS.secondary,
      x: 41.45,
      y: 2244.22
    });
    
    figma.notify(locale().notifications.generated);
    figma.currentPage.selection = [reportFrame];
    figma.viewport.scrollAndZoomIntoView([reportFrame]);
    
  } catch (error) {
    console.error('Error:', error);
    figma.notify(locale().notifications.failed + (error.message || locale().notifications.unknown));
  }
}
